sudo: false
addons:
  apt:
    packages:
    - lftp
    - curl
os: linux
language: generic
script:
  - lftp -e "set sftp:auto-confirm yes; mirror -Rev --exclude-glob .git* --exclude .git/ . ./web/data; quit" -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST
  - curl --silent $POST_DEPLOYMENT_URL > /dev/null