sudo: false
addons:
  apt:
    packages:
    - lftp
    - curl
os: linux
language: generic
script:
  - lftp -e "mirror -Rev --exclude-glob .git* --exclude .git/ . ./web/data; quit" -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST
  - curl --silent $POST_DEPLOYMENT_URL > /dev/null